In [1]:
import pandas as pd
import os
import glob
#glob documentation here and here:
##https://docs.python.org/3/library/glob.html
###https://stackoverflow.com/questions/37080132/use-pandas-and-glob-to-merge-numerous-csv-data-text-files-from-a-directory

In [4]:
#point to the folder housing the data
path = "CitiBikeData"

#glob all the csvs
all_csvs = glob.glob(os.path.join(path, "*csv"))

#make dataframes for all the csv files
df_all = (pd.read_csv(f) for f in all_csvs)

#concatenate the dataframes
concatenated_df = pd.concat(df_all, ignore_index=True)
concatenated_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,74A4206E7487CBC9,docked_bike,2021-05-23 16:51:00,2021-05-23 18:38:21,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
1,58EEE2950FFE01CE,docked_bike,2021-05-31 16:54:47,2021-05-31 16:55:28,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,member
2,1429D912C16EEE59,docked_bike,2021-05-25 16:19:34,2021-05-25 17:03:06,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
3,FE9C5B74167CBCCD,docked_bike,2021-05-22 17:32:19,2021-05-22 17:41:27,9 St HBLR - Jackson St & 8 St,HB305,Grand St & 2 St,HB405,40.747907,-74.038411,40.739130,-74.036180,casual
4,B88D37626F000BBA,docked_bike,2021-05-14 09:48:34,2021-05-14 10:17:36,Union St,JC051,Newark Ave,JC032,40.718211,-74.083639,40.721525,-74.046305,casual

In [5]:
#output the concatenated data to a csv
concatenated_df.to_csv("CitiBikeData/citibike_567_2021.csv")